[workspace]
resolver = "2"
members = ["backend", "macros"]

[profile.dev]
opt-level = 1
incremental = true
debug = false

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
