services:
  backend:
    image: ${IMAGE_NAMESPACE}/backend:latest
    container_name: backend
    restart: always
    networks:
      - backend_net
    environment:
      - DOMAIN=${DOMAIN}
      - MAIL_SERVER="mail:1025"
      - STORE_SUFFIX=${STORE_SUFFIX}
      - ROOT_DB_NAME=${ROOT_DB_NAME}
      - ATLAS_URI=${ATLAS_URI}
      - STORAGE_URI=${STORAGE_URI}
      - STORAGE_REGION=${STORAGE_REGION}
      - STORAGE_USER=${STORAGE_USER}
      - STORAGE_PASSWORD=${STORAGE_PASSWORD}
      - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}

  cache:
    image: ${IMAGE_NAMESPACE}/cache:latest
    container_name: cache
    restart: always
    networks:
      - backend_net

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    networks:
      - backend_net
    environment:
      - MINIO_ROOT_USER=${STORAGE_USER}
      - MINIO_ROOT_PASSWORD=${STORAGE_PASSWORD}
    command: server /data
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 && mc alias set myminio http://minio:9000 ${STORAGE_USER} ${STORAGE_PASSWORD} &&
      mc mb -p myminio/${STORAGE_BUCKET_NAME} || true &&
      mc anonymous set download myminio/${STORAGE_BUCKET_NAME}
      "
    networks:
      - backend_net

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    networks:
      - backend_net
    volumes:
      - mongo_data:/data/db
    profiles:
      - "mongo-local"

  caddy: &caddy_base
    image: ${IMAGE_NAMESPACE}/proxy:latest
    container_name: proxy
    restart: always
    networks:
      - backend_net
    environment:
      - DOMAIN=${DOMAIN}
      - ACME_EMAIL=${ACME_EMAIL}
      - ACME_CA=${ACME_CA}
      - STORE_SUFFIX=${STORE_SUFFIX}
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.caddy.entrypoints=websecure"
      - "traefik.tcp.routers.caddy.rule=HostSNI(`${DOMAIN}`) || HostSNIRegexp(`.*\\.${STORE_SUFFIX}`)"
      - "traefik.tcp.routers.caddy.tls.passthrough=true"
      - "traefik.tcp.services.caddy.loadbalancer.server.port=443"
      - "traefik.tcp.routers.caddy-catchall.entrypoints=websecure"
      - "traefik.tcp.routers.caddy-catchall.rule=HostSNIRegexp(`.*`)"
      - "traefik.tcp.routers.caddy-catchall.priority=1"
      - "traefik.tcp.routers.caddy-catchall.tls.passthrough=true"
      - "traefik.tcp.routers.caddy-catchall.service=caddy"
    # HTTP configurations
    # - "traefik.http.routers.http-catchall.entrypoints=web"
    # - "traefik.http.routers.http-catchall.rule=PathPrefix(`/`)"
    # - "traefik.http.routers.http-catchall.priority=1"
    # - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
    # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    # - "traefik.http.middlewares.redirect-to-https.redirectscheme.port=443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  caddy-standalone:
    <<: *caddy_base
    container_name: caddy-standalone
    ports:
      - "80:80"
      - "443:443"
    labels: []
    profiles:
      - "standalone"

  mail:
    image: axllent/mailpit:latest
    container_name: mail
    restart: always
    environment:
      - MP_UI_AUTH=${MP_UI_AUTH}
    networks:
      - backend_net

networks:
  backend_net:

volumes:
  minio_data:
  mongo_data:
  caddy_data:
  caddy_config:
