version: '3'

tasks:
  default:
    deps: [proxy, database, minio, backend, frontend]
  backend:
    deps: [api]
  api:
    silent: true
    log: true
    cmds:
      - cd backend && cargo watch -x 'run'
  minio:
    silent: true
    log: true
    cmds:
      - minio server /tmp/data --console-address ":9001"
  database:
    silent: true
    log: true
    cmds:
      - ./scripts/run-db.sh
  proxy:
    silent: true
    log: true
    cmds:
      - ./scripts/run-proxy.sh
  frontend:
    silent: true
    log: true
    cmds:
      - ./scripts/run-front.sh
