version: '3'

tasks:
  default:
    deps: [entry, db, minio, backend, frontend]
  backend:
    deps: [api, web, gate]
  api:
    cmds:
      - cd backend && cargo watch -x 'run --bin api' &> ../logs/api
  web:
    cmds:
      - cd backend && cargo watch -x 'run --bin web' &> ../logs/web
  gate:
    cmds:
      - cd backend && cargo watch -x 'run --bin gate' &> ../logs/gate
  
  minio:
    cmds:
      - minio server /tmp/data --console-address ":9001" &> logs/minio
  db:
    cmds:
      - ./scripts/run-db.sh &> logs/db
  entry:
    cmds:
      - ./scripts/run-proxy.sh &> logs/proxy
  frontend:
    cmds:
      - ./scripts/run-front.sh &> logs/frontend
