[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common", features = ["server"] }
axum = "0.8.1"
axum-extra = { version = "0.10.0", features = ["cookie"] }
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
field = "0.1.0"
futures = "0.3.31"
hyper = { version = "1.6.0", features = ["full"] }
jsonwebtoken = "9.3.1"
serde = "1.0.219"
tokio = { version = "1.44.1", features = ["full"] }
tower = "0.5.2"
tower-cookies = "0.11.0"
tower-http = { version = "0.6.2", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
mongodb = "3.2.3"
